version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: inventario
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app/data:/app/data
    depends_on:
      - redis
      - rabbitmq
      - mailhog

  worker:
    build: .
    command: python worker.py
    depends_on:
      - rabbitmq
      - mailhog

volumes:
  postgres_data: