version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: inventario
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      DB_HOST: db
      DB_NAME: inventario
      DB_USER: admin
      DB_PASSWORD: admin123
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
      - rabbitmq

  worker:
    build: .
    command: python worker.py
    depends_on:
      - rabbitmq
      - mailhog

volumes:
  postgres_data: